camera_basic_controls:
  ros__parameters:
    qos_image_publish_reliable: True
    camera_settings:
      TriggerMode: Off
      GainAuto: Off
      Gain: 18
      AcquisitionFrameRateAuto: Off
      AcquisitionFrameRateEnabled: True
      AcquisitionFrameRate: 100

camera_with_settings:
  ros__parameters:
    qos_image_publish_reliable: True
    add_timestamp: True
    publish_grayscale: True
    publish_color: False
    latch_timing_interval_s: 5
    reset_camera_settings: False
    camera_settings:
      TriggerMode: "Off"
      GainAuto: "Continuous"
      AcquisitionFrameRateAuto: "Off"
      AcquisitionFrameRateEnabled: True
      AcquisitionFrameRate: 50
      BinningVertical: 2
      unknown_param: "test, test"
    camera_chunkdata:
      FrameCounter:
        ChunkEnable: True
        ChunkModeActive: True
      randomChunk:
        blabla: False
      Timestamp:
        ChunkEnable: True
        ChunkModeActive: True

camera_with_id:
  ros__parameters:
    qos_image_publish_reliable: True
    cam_id: 18518215

camera_with_reset:
  ros__parameters:
    qos_image_publish_reliable: True
    add_timestamp: True
    reset_camera_settings: True

camera_with_custom_topic:
  ros__parameters:
    qos_image_publish_reliable: True
    cam_id: 18518215
    image_topic: "special_camera/example_image_topic_name"
