# grasshopper
"18517933":
  TriggerMode: "Off"
  GainAuto: "Off"
  AcquisitionFrameRateAuto: "Off"
  AcquisitionFrameRateEnabled: True
  AcquisitionFrameRate: 50
  LineSelector: "Line3" # PySpin.LineSelector_Line3
  LineMode: "Output"
  LineSource: "ExposureActive"
  LineInverter: True
  AutoFunctionAOIsControl: "On"
  Width: 512
  Height: 512
  OffsetX: 500
  OffsetY: 500
  BinningVertical: 2
# chameleon
"18518215":
  BinningVertical: 2
  TriggerMode: "Off"
  GainAuto: "Off"
  AcquisitionFrameRateAuto: "Off"
  AcquisitionFrameRateEnabled: True
  AcquisitionFrameRate: 100
  LineSelector: "Line3" # PySpin.LineSelector_Line3
  LineMode: "Output"
  LineSource: "ExposureActive"
  LineInverter: True
  # ExposureMode: "Timed"
  # ExposureAuto: "Off"
  # ExposureTime: 8000
  Width: 256
  Height: 256
  OffsetX: 128
  OffsetY: 128

"18318588":
  BinningVertical: 2
  TriggerMode: "Off"
  GainAuto: "Off"
  AcquisitionFrameRateAuto: "Off"
  AcquisitionFrameRateEnabled: True
  AcquisitionFrameRate: 100
  LineSelector: "Line3" # PySpin.LineSelector_Line3
  LineMode: "Output"
  LineSource: "ExposureActive"
  LineInverter: True
  # ExposureMode: "Timed"
  # ExposureAuto: "Off"
  # ExposureTime: 8000
  Width: 256
  Height: 256
  OffsetX: 128
  OffsetY: 128

"18421877":
  BinningVertical: 2
  TriggerMode: "Off"
  GainAuto: "Off"
  AcquisitionFrameRateAuto: "Off"
  AcquisitionFrameRateEnabled: True
  AcquisitionFrameRate: 100
  LineSelector: "Line3" # PySpin.LineSelector_Line3
  LineMode: "Output"
  LineSource: "ExposureActive"
  LineInverter: True
  # ExposureMode: "Timed"
  # ExposureAuto: "Off"
  # ExposureTime: 8000
  Width: 256
  Height: 256
  OffsetX: 128
  OffsetY: 128
