basic_example_camera:
  ros__parameters:
    config_found: True
    image_topic: "camera/image_mono"
    latency_topic: "camera/latency"
    add_timestamp: True
    publish_grayscale: True
    publish_color: False
    latch_timing_interval_s: 5
    reset_camera_settings: False
    camera_settings:
      TriggerMode: "Off"
      GainAuto: "Continuous"
      AcquisitionFrameRateAuto: "Off"
      AcquisitionFrameRateEnabled: True
      AcquisitionFrameRate: 50
      LineSelector: "Line3"
      LineMode: "Output"
      LineSource: "ExposureActive"
      LineInverter: True
      AutoFunctionAOIsControl: "On"
      BinningVertical: 2
    camera_chunkdata:
      FrameCounter:
        ChunkEnable: True
        ChunkModeActive: True
      Timestamp:
        ChunkEnable: True
        ChunkModeActive: True
camera_test_off:
  ros__parameters:
    config_found: True
    image_topic: "camera/image_mono"
    latency_topic: "camera/latency"
    publish_grayscale: True
    publish_color: False
    camera_settings:
      TriggerMode: Off
      GainAuto: Off
      AcquisitionFrameRateAuto: Off
      AcquisitionFrameRateEnabled: True
      AcquisitionFrameRate: 50
      LineSelector: "Line3"
      LineMode: "Output"
      LineSource: "ExposureActive"
      LineInverter: True
      AutoFunctionAOIsControl: On
    camera_chunkdata:
      FrameCounter:
        ChunkEnable: True
        ChunkModeActive: True
      Timestamp:
        ChunkEnable: True
        ChunkModeActive: True
camera_test_id:
  ros__parameters:
    config_found: True
    image_topic: "camera/image_mono"
    latency_topic: "camera/latency"
    cam_id: 18518215
    publish_grayscale: True
    publish_color: True
