camera1:
  ros__parameters:
    config_found: True
    reset_camera_settings: True
    cam_id: "18497067"
    camera_topic_base: "camera/rig1_ball"
    publish_grayscale: True
    publish_color: False
    camera_settings:
      # AutoFunctionAOIsControl: "On" # not sure what this setting does
      TriggerMode: "Off"
      GainAuto: "Off"
      AcquisitionFrameRateEnabled: True
      AcquisitionFrameRateAuto: "Off"
      AcquisitionFrameRate: 120.0 # max around 400, image does get dark
      LineSelector: "Line3" # PySpin.LineSelector_Line3
      LineMode: "Output"
      LineSource: "ExposureActive"
      LineInverter: True
      BinningVertical: 2 #automatically bins horizontal as well
      Width: 400
      Height: 368
      OffsetX: 160
      OffsetY: 0
    camera_chunkdata:
      FrameCounter:
        ChunkEnable: True
        ChunkModeActive: True
      Timestamp:
        ChunkEnable: True
        ChunkModeActive: True
# don't do indent
