camera1:
  ros__parameters:
    config_found: True
    cam_id: "18518215"
    # cam_id: "18421586"
    reset_camera_settings: True
    camera_topic: "camera/rig1_ball/image_mono"
    publish_grayscale: True
    publish_color: False
    camera_settings:
      # AutoFunctionAOIsControl: "On" # not sure what this setting does
      TriggerMode: "Off"
      GainAuto: "Off"
      AcquisitionFrameRateAuto: "Off"
      AcquisitionFrameRateEnabled: True
      AcquisitionFrameRate: 50
      LineSelector: "Line3" # PySpin.LineSelector_Line3
      LineMode: "Output"
      LineSource: "ExposureActive"
      LineInverter: True
      AutoFunctionAOIsControl: "On"
      # Width: 512
      # Height: 512
    camera_chunkdata:
      FrameCounter:
        ChunkEnable: True
        ChunkModeActive: True
      Timestamp:
        ChunkEnable: True
        ChunkModeActive: True
camera2:
  ros__parameters:
    config_found: True
    # cam_id: "18318588"
    reset_camera_settings: True
    # cam_id: "20400128"
    cam_id: "18518215"
    camera_topic: "camera/rig2_ball/image"
    publish_grayscale: True
    publish_color: False
    camera_settings:
      TriggerMode: 0
      GainAuto: 0
      # AcquisitionFrameRateEnable: 0
      AcquisitionFrameRate: 120.0 # max around 400, image does get dark
      # LineSelector: "Line3" # PySpin.LineSelector_Line3
      # LineMode: "Output"
      # LineSource: "ExposureActive"
      # LineInverter: True
      BinningVertical: 2 #automatically bins horizontal as well
      Width: 400
      Height: 368
      OffsetX: 160
      OffsetY: 0
    camera_chunkdata:
      FrameCounter:
        ChunkEnable: True
        ChunkModeActive: True
      Timestamp:
        ChunkEnable: True
        ChunkModeActive: True
